import "./globals.scss";
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import Providers from "./providers";
import { ChatMessageProvider } from "./context/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`min-h-screen bg antialiased`}>
        <Providers>
          <ChatMessageProvider>
            <div className=" flex flex-col justify-between min-h-screen">
              <div className="mb-auto">{children}</div>
            </div>
          </ChatMessageProvider>
        </Providers>
      </body>
    </html>
  );
}
